### ISSUE TITLE
._isSelected ()

### ISSUE THREAD

**Issue by duaraghav8** [parkjs814/AlgorithmVisualizer#77]
I think it would be good if we had tracer._isSelected () to determine if a particular element is selected or not.
Its not absolutely necessary, but I think it makes some tasks much easier. I've felt the need on several occasions.

**Comment by parkjs814** [comment]
Due to the memory problem, it is not favorable to save data for every steps.
So that if we really want to create _isSelected() method, it should depend on the visualized result (such as checking whether table-cell is colored red or not).
However, since the visualized result comes out after finishing execution of code pieces, it is contradictory to reference the future outcome.

**Comment by TornjV** [comment]
This could easily done with an additional array added to your code if needed.
Closing for now.
